language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-pattern-lab' ]; then cd .. && eval "mv $currentfolder generator-pattern-lab" && cd generator-pattern-lab; fi
